### ISSUE TITLE
Can this be updated for the last jtupdate?

### ISSUE THREAD

**Issue by manichispanic999** [espiox/openfpga-multi-cores#1]
There's been another update from jotego for these cores, can yours be updated as well? Thanks

**Comment by espiox** [comment]
Yep! I skipped the last update because there weren’t major changes, but I’ll be updating to today’s release later this evening.

**Comment by manichispanic999** [comment]
Thanks! and of course it looks like he updated it again XD

**Comment by espiox** [comment]
I’m aware, but there are no System 16 changes in that update. JT’s system pushes new releases for all cores, even if only one is changed - in this case only jtdd was actually updated. 

I’ll probably update the files later today just so things match.
